  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Messaging'
  pod 'Firebase/Storage'
  pod 'SVProgressHUD','2.2.5'
  pod 'GoogleSignIn'

  pod 'GoogleMaps'
  pod 'GooglePlaces'
  pod 'GooglePlacePicker'
  pod 'Loki', :git => 'https://github.com/myselflokeshyadav/Loki.git'
  pod 'DLRadioButton', '~> 1.4'

  pod 'Fabric', '~> 1.9.0'
  pod 'Crashlytics', '~> 3.12.0'
  pod 'TWMessageBarManager'